INSERT INTO [dbo].[Rooms] VALUES (N'PC učebna I.', N'B124')
INSERT INTO [dbo].[Rooms] VALUES (N'PC učebna II.', N'B217')
INSERT INTO [dbo].[Rooms] VALUES (N'PC učebna III.', N'B219')
INSERT INTO [dbo].[Rooms] VALUES (N'PC učebna IV.', N'B303')
INSERT INTO [dbo].[Rooms] VALUES (N'PC učebna V.', N'B313')
INSERT INTO [dbo].[Rooms] VALUES (N'PC učebna VI.', N'B314')
INSERT INTO [dbo].[Rooms] VALUES (N'PC učebna VII.', N'A144')
INSERT INTO [dbo].[Rooms] VALUES (N'PC učebna VIII.', N'A211')
INSERT INTO [dbo].[Rooms] VALUES (N'PC učebna IX.', N'D006')
INSERT INTO [dbo].[Rooms] VALUES (N'Učitelé', N'UCIT')

INSERT INTO [dbo].[Computers] VALUES (N'B313-00', N'Učitelský počítač v B313',N'ahoj', N'AMD', 8, 512, 0, 5)
INSERT INTO [dbo].[Computers] VALUES (N'B313-01', N'První řada u okna', N'ahoj',N'AMD', 8, 512, 0, 5)
INSERT INTO [dbo].[Computers] VALUES (N'B313-02', N'První řada, druhý od okna', N'ahoj',N'AMD', 8, 512, 0, 5)
INSERT INTO [dbo].[Computers] VALUES (N'Notebook-ST', N'HP Notebook (Stehlík)',N'ahoj', N'AMD', 16, 1024, 0, 10)
INSERT INTO [dbo].[Computers] VALUES (N'B314-00', N'Učitelský počítač v B314', N'ahoj',N'AMD', 8, 512, 1, 6)
INSERT INTO [dbo].[Computers] VALUES (N'B314-01', N'První počítač v B314', N'ahoj',N'AMD', 8, 512, 0, 6)
